name: Projects  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /peoples get lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-g.zip peoples/get/index.js node_modules
      - name: people get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-g
            zip_file: m-s-peoples-g.zip
      - name: /peoples post lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-po.zip peoples/post/index.js node_modules
      - name: people get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-po
            zip_file: m-s-peoples-po.zip
      - name: /peoples/{people_id} get lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-people-g.zip peoples/people_id/get/index.js node_modules
      - name: people get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-people-g
            zip_file: m-s-peoples-people-g.zip
      - name: /peoples/{people_id} put lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-people-pu.zip peoples/people_id/put/index.js node_modules
      - name: people get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-people-pu
            zip_file: m-s-peoples-people-pu.zip
      - name: /peoples/{people_id} delete lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-people-d.zip peoples/people_id/delete/index.js node_modules
      - name: people get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-people-d
            zip_file: m-s-peoples-people-d.zip          
      - name: /peoples/{people_id}/tags get lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-people-tags-g.zip peoples/people_id/tags/get/index.js node_modules
      - name: peoples get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-people-tags-g
            zip_file: m-s-peoples-people-tags-g.zip
      - name: /peoples/{people_id}/tags post lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-people-tags-po.zip peoples/people_id/tags/post/index.js node_modules
      - name: peoples get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-people-tags-po
            zip_file: m-s-peoples-people-tags-po.zip
      - name: /peoples/{people_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/peoples@main
        with:
            args: zip -qq -r m-s-peoples-people-tags-tag-d.zip peoples/people_id/tags/tag_id/delete/index.js node_modules
      - name: peoples get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoples-people-tags-tag-d
            zip_file: m-s-peoples-people-tags-tag-d.zip            
      - name: /peoples/bookmarklet get lambda deploy zip
        uses: kinlane/peoples@main
        with:
            args: zip -qq -r m-s-peoplesbookmarklet-g.zip peoples/bookmarklet/get/index.js node_modules
      - name: peoples get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-peoplesbookmarklet-g
            zip_file: m-s-peoplesbookmarklet-g.zip  
                                  